language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - python3
env:
 - DIR=solr COMMAND="ant -Dtests.class=org.apache.solr.client.solrj.io.* test"
 - DIR=solr COMMAND="ant -Dtests.class=org.apache.solr.handler.TestSQLHandler test"
matrix:
  fast_finish: true
script:
  - ant ivy-bootstrap
  - cd $DIR
  - $COMMAND
